# Parsing MLS Roaster Page

![la galaxy 2018 roster mlssoccer com](https://user-images.githubusercontent.com/872296/41433129-5871915c-6fee-11e8-9ce3-32f5dab9764b.png)

In [1]:
import pandas as pd
import numpy as np

##### Step 1: Read the right table:

In [2]:
page = pd.read_html(
    'https://www.mlssoccer.com/rosters/2018/la-galaxy',
    attrs={'class': "activethirty"})

In [3]:
len(page)

1

In [4]:
df = page[0]

A preview of the table parsed:

In [5]:
df

,30-man Active Roster (Spots 1-30),#,POS,ROSTER STATUSR.S.,PLAYER CATEGORYCAT.,NOTE
0,"Alessandrini, Romain",7.0,M,SeniorSR,"DP, INTL",NaN
1,"Arellano, Hugo",21.0,D,ReserveRES,HG,NaN
2,"Bingham, David",1.0,GK,SeniorSR,NaN,NaN
3,"Boateng, Emmanuel",24.0,M,SeniorSR,NaN,NaN
4,"Carrasco, Servando",14.0,M,SupplementalSUP,NaN,NaN
5,"Ciani, Michael",28.0,D,SeniorSR,INTL,NaN
6,"Cole, Ashley",3.0,D,SeniorSR,INTL,NaN
7,"dos Santos, Giovani",10.0,F,SeniorSR,"DP, INTL",NaN
8,"dos Santos, Jonathan",8.0,M,SeniorSR,"DP, INTL",NaN
9,"Feltscher, Rolf",25.0,D,"SeniorSR, Disabled ListDL",INTL,Disabled ListDL
10,"Hilliard-Arce, Tomas",20.0,D,SupplementalSUP,NaN,NaN
11,"Husidic, Baggio",6.0,M,SeniorSR,NaN,NaN
12,"IbrahimoviÄ‡, Zlatan",9.0,F,SeniorSR,INTL,NaN
13,"Jamieson, Bradford",38.0,F,ReserveRES,HG,NaN
14,"Kamara, Ola",11.0,F,SeniorSR,NaN,NaN
15,"Kitchen, Perry",2.0,M,SeniorSR,NaN,NaN
16,"Lassiter, Ariel",15.0,F,ReserveRES,HG,NaN
17,"Lletget, Sebastian",17.0,M,SeniorSR,NaN,NaN
18,"Pedro, Joao",88.0,M,SeniorSR,INTL,NaN
19,"Pontius, Chris",19.0,F,SeniorSR,NaN,NaN
20,"Romney, Dave",4.0,D,SeniorSR,NaN,NaN
21,"Skjelvik, Jorgen",16.0,D,SeniorSR,INTL,NaN
22,"Steres, Daniel",5.0,D,SeniorSR,NaN,NaN
23,"Sylvestre, Brian",12.0,GK,SupplementalSUP,NaN,NaN
24,"Vom Steeg, Justin",41.0,GK,ReserveRES,NaN,NaN
25,"Williams, Sheanon",NaN,NaN,SupplementalSUP,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN
30,26 of 30 spots filled,NaN,NaN,NaN,NaN,NaN
31,Players that do not count against the 30-man a...,NaN,NaN,NaN,NaN,NaN
32,"Alvarez, Efrain",NaN,NaN,"ReserveRES, On loanOL",Loaned to: USLOL: USL,NaN

The issues we can quickly spot are:

1. The index should probably be the player's name.
2. Roaster Status seems to have a few appended values that are strange (SR, SUP, etc)
3. There are NaNs and then a final note which are not part of the table _"26 of 30 spots filled"_

##### Step 2: Renaming columns to more convenient names

In [6]:
df.columns = ['Player', 'Number', 'Position', 'Roster Status', 'Player Category', 'Notes']
df.head()

,Player,Number,Position,Roster Status,Player Category,Notes
0,"Alessandrini, Romain",7.0,M,SeniorSR,"DP, INTL",NaN
1,"Arellano, Hugo",21.0,D,ReserveRES,HG,NaN
2,"Bingham, David",1.0,GK,SeniorSR,NaN,NaN
3,"Boateng, Emmanuel",24.0,M,SeniorSR,NaN,NaN
4,"Carrasco, Servando",14.0,M,SupplementalSUP,NaN,NaN

##### Step 3: Removing NaNs and not row players

In [7]:
df.dropna(how='all', inplace=True)

In [8]:
df

,Player,Number,Position,Roster Status,Player Category,Notes
0,"Alessandrini, Romain",7.0,M,SeniorSR,"DP, INTL",NaN
1,"Arellano, Hugo",21.0,D,ReserveRES,HG,NaN
2,"Bingham, David",1.0,GK,SeniorSR,NaN,NaN
3,"Boateng, Emmanuel",24.0,M,SeniorSR,NaN,NaN
4,"Carrasco, Servando",14.0,M,SupplementalSUP,NaN,NaN
5,"Ciani, Michael",28.0,D,SeniorSR,INTL,NaN
6,"Cole, Ashley",3.0,D,SeniorSR,INTL,NaN
7,"dos Santos, Giovani",10.0,F,SeniorSR,"DP, INTL",NaN
8,"dos Santos, Jonathan",8.0,M,SeniorSR,"DP, INTL",NaN
9,"Feltscher, Rolf",25.0,D,"SeniorSR, Disabled ListDL",INTL,Disabled ListDL
10,"Hilliard-Arce, Tomas",20.0,D,SupplementalSUP,NaN,NaN
11,"Husidic, Baggio",6.0,M,SeniorSR,NaN,NaN
12,"IbrahimoviÄ‡, Zlatan",9.0,F,SeniorSR,INTL,NaN
13,"Jamieson, Bradford",38.0,F,ReserveRES,HG,NaN
14,"Kamara, Ola",11.0,F,SeniorSR,NaN,NaN
15,"Kitchen, Perry",2.0,M,SeniorSR,NaN,NaN
16,"Lassiter, Ariel",15.0,F,ReserveRES,HG,NaN
17,"Lletget, Sebastian",17.0,M,SeniorSR,NaN,NaN
18,"Pedro, Joao",88.0,M,SeniorSR,INTL,NaN
19,"Pontius, Chris",19.0,F,SeniorSR,NaN,NaN
20,"Romney, Dave",4.0,D,SeniorSR,NaN,NaN
21,"Skjelvik, Jorgen",16.0,D,SeniorSR,INTL,NaN
22,"Steres, Daniel",5.0,D,SeniorSR,NaN,NaN
23,"Sylvestre, Brian",12.0,GK,SupplementalSUP,NaN,NaN
24,"Vom Steeg, Justin",41.0,GK,ReserveRES,NaN,NaN
25,"Williams, Sheanon",NaN,NaN,SupplementalSUP,NaN,NaN
30,26 of 30 spots filled,NaN,NaN,NaN,NaN,NaN
31,Players that do not count against the 30-man a...,NaN,NaN,NaN,NaN,NaN
32,"Alvarez, Efrain",NaN,NaN,"ReserveRES, On loanOL",Loaned to: USLOL: USL,NaN

In [9]:
df.loc[df['Player'].str.contains('spots filled')]

                   Player  Number Position Roster Status Player Category Notes
30  26 of 30 spots filled     NaN      NaN           NaN             NaN   NaN

In [10]:
df.index.get_indexer_for(df.loc[df['Player'].str.contains('spots filled')].index)

array([26])

In [11]:
index_col = df.index.get_indexer_for(df.loc[df['Player'].str.contains('spots filled')].index)[0]
index_col

26

In [12]:
df.iloc[index_col:]

,Player,Number,Position,Roster Status,Player Category,Notes
30,26 of 30 spots filled,NaN,NaN,NaN,NaN,NaN
31,Players that do not count against the 30-man a...,NaN,NaN,NaN,NaN,NaN
32,"Alvarez, Efrain",NaN,NaN,"ReserveRES, On loanOL",Loaned to: USLOL: USL,NaN

In [13]:
df.drop(df.iloc[index_col:].index)

,Player,Number,Position,Roster Status,Player Category,Notes
0,"Alessandrini, Romain",7.0,M,SeniorSR,"DP, INTL",NaN
1,"Arellano, Hugo",21.0,D,ReserveRES,HG,NaN
2,"Bingham, David",1.0,GK,SeniorSR,NaN,NaN
3,"Boateng, Emmanuel",24.0,M,SeniorSR,NaN,NaN
4,"Carrasco, Servando",14.0,M,SupplementalSUP,NaN,NaN
5,"Ciani, Michael",28.0,D,SeniorSR,INTL,NaN
6,"Cole, Ashley",3.0,D,SeniorSR,INTL,NaN
7,"dos Santos, Giovani",10.0,F,SeniorSR,"DP, INTL",NaN
8,"dos Santos, Jonathan",8.0,M,SeniorSR,"DP, INTL",NaN
9,"Feltscher, Rolf",25.0,D,"SeniorSR, Disabled ListDL",INTL,Disabled ListDL
10,"Hilliard-Arce, Tomas",20.0,D,SupplementalSUP,NaN,NaN
11,"Husidic, Baggio",6.0,M,SeniorSR,NaN,NaN
12,"IbrahimoviÄ‡, Zlatan",9.0,F,SeniorSR,INTL,NaN
13,"Jamieson, Bradford",38.0,F,ReserveRES,HG,NaN
14,"Kamara, Ola",11.0,F,SeniorSR,NaN,NaN
15,"Kitchen, Perry",2.0,M,SeniorSR,NaN,NaN
16,"Lassiter, Ariel",15.0,F,ReserveRES,HG,NaN
17,"Lletget, Sebastian",17.0,M,SeniorSR,NaN,NaN
18,"Pedro, Joao",88.0,M,SeniorSR,INTL,NaN
19,"Pontius, Chris",19.0,F,SeniorSR,NaN,NaN
20,"Romney, Dave",4.0,D,SeniorSR,NaN,NaN
21,"Skjelvik, Jorgen",16.0,D,SeniorSR,INTL,NaN
22,"Steres, Daniel",5.0,D,SeniorSR,NaN,NaN
23,"Sylvestre, Brian",12.0,GK,SupplementalSUP,NaN,NaN
24,"Vom Steeg, Justin",41.0,GK,ReserveRES,NaN,NaN
25,"Williams, Sheanon",NaN,NaN,SupplementalSUP,NaN,NaN

In [14]:
df.drop(df.iloc[index_col:].index, inplace=True)

##### Step 4: Cleaning Roaster Status

In [15]:
df['Roster Status'].unique()

array(['SeniorSR', 'ReserveRES', 'SupplementalSUP',
       'SeniorSR, Disabled ListDL'], dtype=object)

In [16]:
df['Roster Status'].str.split(',', expand=True)

                  0                 1
0          SeniorSR              None
1        ReserveRES              None
2          SeniorSR              None
3          SeniorSR              None
4   SupplementalSUP              None
5          SeniorSR              None
6          SeniorSR              None
7          SeniorSR              None
8          SeniorSR              None
9          SeniorSR   Disabled ListDL
10  SupplementalSUP              None
11         SeniorSR              None
12         SeniorSR              None
13       ReserveRES              None
14         SeniorSR              None
15         SeniorSR              None
16       ReserveRES              None
17         SeniorSR              None
18         SeniorSR              None
19         SeniorSR              None
20         SeniorSR              None
21         SeniorSR              None
22         SeniorSR              None
23  SupplementalSUP              None
24       ReserveRES              None
25  SupplementalSUP              None